### ISSUE TITLE
Plots for prisms demo

### ISSUE THREAD

**Issue by svoinea** [informatics-isi-edu/deriva-webapps#10]
We need to have a simple web app that plots a series of x-y line plots.  This should be done using plotly.  We have a specific set of tables that need to be queried and x and y values come from known columns. 

Plotly app should be set up so that lines can be turned on and off.

For fancy application, we can try using the plot.ly streaming interfaces, but to start just pulling a fixed number of points from ERMRest is ok.

Exact queries to follow.

**Comment by svoinea** [comment]
We can start with the `prisms.breathe_platform_airbeam_view_dev_ft` table, with the columns:
 - x = `recorded_time` (a timestamp with time zone)
 - y = `pm_value` (a real)

If the plot supports multiple `y`, then other 2 columns for `y` might be `f_value` and `rh_value` (both are `smallint`).

**Comment by carlkesselman** [comment]
Looks like we might actually want to make this reachable from a record page, rather then the nav bar, so it would be just like the heat map…. for this record find the X and Y values from a specific set of related tables and plot them.

Carl

----------------------------------------------------------
Dr. Carl Kesselman
Dean’s Professor, Epstein Department of Industrial and Systems Engineering
Fellow, Information Sciences Institute
Viterbi School of Engineering

Professor, Preventive Medicine
Keck School of Medicine

University of Southern California
4676 Admiralty Way, Suite 1001, Marina del Rey, CA  90292-6695
Phone:  +1 (310) 448-9338
Email:  carl@isi.edu<mailto:carl@isi.edu>
Web: http://www.isi.edu/~carl








On Oct 15, 2018, at 2:55 PM, svoinea <notifications@github.com<mailto:notifications@github.com>> wrote:


We can start with the prisms.breathe_platform_airbeam_view_dev_ft table, with the columns:

  *   x = recorded_time (a timestamp with time zone)
  *   y = pm_value (a real)

If the plot supports multiple y, then other 2 columns for y might be f_value and rh_value (both are smallint).

**Comment by hongsudt** [comment]
@carlkesselman @svoinea  The plot will support multiple independent lines. Please list initial lines that you want to display. I want the detail of table, x-axis, y-axis for each line. So far: I saw
- line 1: 
  - table: prisms.breath_platform_airbeam_view_dev_ft, 
  - x-axis: recorded_time
  - y-axis: pm_value
- line 2: 
  - table: prisms.breath_platform_airbeam_view_dev_ft, 
  - x-axis: recorded_time
  - y-axis: f_value
- line 3: 
  - table: prisms.breath_platform_airbeam_view_dev_ft, 
  - x-axis: recorded_time
  - y-axis: rh_value
- line 4: 
- line 5:

Please note that if the y-range between lines are so dramatically different, then your line plot will only demonstrate the trend e.g. you won't be able to see the detail unless you zoom in. 

Will each one of those lines have the same column name for the subject to be filtered? If so, what's the subject column name?

**Comment by svoinea** [comment]
Attached the file sent by Jose Luis:

[subject_value_comb_to_plot-DS-JLA.xlsx](https://github.com/informatics-isi-edu/deriva-webapps/files/2485251/subject_value_comb_to_plot-DS-JLA.xlsx)

**Comment by svoinea** [comment]
Actually the real tables have the `_view_dev_ft` suffix in their names.
The tables w/o that suffix are just empty tables.

**Comment by svoinea** [comment]
The `x` axis for all the tables is `recorded_time`.

The `subject_id` for all the tables is `159`.

The starting display time is `2018-10-15 12:00:00`.

Let's display the following lines:
 - line 1
   - table `prisms:breathe_platform_airbeam_view_dev_ft`
   - y-axis `pm_value`
 - line 2
   - table `prisms:breathe_platform_airbeam_view_dev_ft`
   - y-axis `rh_value`
 - line 3
   - table `prisms:breathe_platform_airbeam_view_dev_ft`
   - y-axis `f_value`
 - line 4
   - table `prisms:breathe_platform_heartrate_view_dev_ft`
   - y-axis `v_value`
 - line 5
   - table `prisms:breathe_platform_spirometer_trigger_view_dev_ft`
   - y-axis `value`

**Comment by jrchudy** [comment]
Changes for this issue have been merged into master. The `lineplot` folder in the root of this repository should have the instructions for installation and an explanation of the configuration file and query parameters.

A working version, using the configuration in `lineplot-config.js`, can be seen here:
https://prisms.isrd.isi.edu/~jchudy/lineplot/

Assigning to @svoinea for verification.

**Comment by svoinea** [comment]
The demo went well.
