### ISSUE TITLE
using resources plot on gudmap homepage

### ISSUE THREAD

**Issue by crisaless** [informatics-isi-edu/deriva-webapps#103]
I'm trying to use iframe to pull in the gudmap resources plot on the new gudmap homepage.

Resources plot: 
https://dev.gudmap.org/deriva-webapps/plot/?config=gudmap-todate-bar

You can see the space I have available (currently using edited static shot):
https://staging.gudmap.org/

Space was designed for about 675px width by 350px high. 
The current dimensions for the resources plot is 1200px by 500px

1. Is it possible to try configuring the plot to be responsive (per this config I found in online doc for plotly.js) https://plotly.com/javascript/responsive-fluid-layout/

2. Is it possible to suppress the navigation via the source URL for the iframe? Right now the navbar appears for a second or two before the rest of the blinks for a second.

3. One of the left side labels is much longer than the rest. Can we shorten "Sequencing: Replicate (Bulk/Single Cell)"? I would vote for just "Sequencing".

**Comment by crisaless** [comment]
So far, I can widen the homepage area for this chart on a laptop view (window width: 1440px) up to 810px.

**Comment by jrchudy** [comment]
Sorry I haven't gotten to this yet Cris. I will take a look at this tomorrow afternoon. To quickly answer some of your questions:
 1. I believe `responsive: true` is already set for all plot types when using `/deriva-webapps/plot`. There might be something else causing the plot and contents to not stretch to the width.
 2. Do you mean the navbar inside the iframe or outside of the iframe?
 3. Those labels come from the database so it might be more difficult adjusting that on the fly unless we add a new option to the configuration.

**Comment by jrchudy** [comment]
1. After looking into what the code is doing for bar graphs, responsive true is already being set. 
  - Like you mentioned, the graph configuration has the height set to 500px and the width set to 1200px
  - this set height and width prevents the `responsive: true` property from fully being responsive to the iframe
  - since responsiveness is affected by the defined height and width, we can define a new plot configuration that has a smaller height and width
    - From testing, `height: 300` and `width: 650` seem to be the best for an iframe with `height: 350px` and `width: 675px`
2. navbar inside the iframe is something from chaise that is not working properly. Will have to open a chaise issue and look into this

**Comment by jrchudy** [comment]
Responsiveness for the plot app has been fixed. One thing to note is that defining a height/width in the "layout" of the plot configuration in `plot-config.js` causes the graph to be drawn at that exact size and ignore the responsiveness.

**Comment by jrchudy** [comment]
Changes for responsiveness have been merged into master. Updated the `plot-config.js` on `dev.rebuidingakidney.org` and will update the config for the recipes again as well. 

@crisaless I added a new configuration to `plot-config.js` called `gudmap-todate-bar-no-dimensions`. This one has no height or width defined which will allow for it to resize to the defined size of the iframe.

**Comment by crisaless** [comment]
Looks good! Thanks!
