### ISSUE TITLE
Update plot app to allow for text links

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/deriva-webapps#106]
The title, xaxis title, yaxis title, ticks for each x/y value, and legend values should all be allowed to be HTML links.

To begin, we will tackle the specific case that was asked for the current configuration named `gudmap-todate-bar`. Each left bar should be templated to point to a recordset page for the given `schema` and `table` returned from the view the data is queried from.

Link to property names and what their types will be:
https://docs.google.com/spreadsheets/d/1TUDp1bhni_FsS0my51qP4QY4NDeSW_TT8gnPJMoLY2w/edit#gid=0

Names and types to be added:
```
{
  plot_type: "",
  ...
  config: {
    title_display_markdown_pattern: "",
    ...
    xaxis: {
      title_display_markdown_pattern: "",
      tick_display_markdown_pattern: ["", ...] || "", // Array of Strings or String (see document)
    },
    yaxis: {
      title_display_markdown_pattern: "",
      tick_display_markdown_pattern: ["", ...] || "", // Array of Strings or String (see document)
    }
  } // end config object
  ...
  traces: [{
    uri: "",
    ...
    legend_markdown_pattern: ["", ...],
    legend_disable_default_click: Boolean, 
    // - true: is to disable
    // - false (default): is to enable
    ...
    graphic_link_pattern: ["", ...] || "", // Array of Strings (see document)
    hovertemplate_display_pattern: "" // for modifying the content of the tooltip
  }, { ...} ]
}
```

Sample configuration for gudmap release all to test all properties above:
```
"gudmap-release-all": {
  page_title: "GUDMAP Data Summary Dashboard",
  plots: [{
    plot_title: "Number of assets created and released",
    plot_type: "bar",
    config: {
      x_axis_type: 'log',
      x_axis_thousands_separator: true,
      format_data_x: true   // defualt : false - to use hack or not
    },
    plotly_config:{
      title_display_markdown_pattern: "[Number of GUDMAP resources created and released to date (log scale)](/chaise/recordset/#2/Dashboard:Release_Status/*::facets::N4IghgdgJiBcDaoDOB7ArgJwMYFM4gGEUJUMAXASzQFsQAaELACxQtyTnhAHEBVAEQCyAQQAKIALoBfaUA)"
      height: 800,
      width: 1200,
      margin: {
        l: 280,  // left margin for lengthy data labels
      },
      legend:{
        traceorder: "reversed"
      },
      xaxis: {
        title_display_markdown_pattern: "[Number of Records](/chaise/recordset/#2/Dashboard:Release_Status)", // link path doesn't make sense but it's just for testing
        tick_display_markdown_pattern: "[{{$self.Data_Type}}](/chaise/recordset/#2/{{$self.Schema_Table}}/::facet::*{{#encodeFacet}}{{$self.Data_Type_Filter}}{{/encodeFacet}}){target=_blank}", // doesn't make sense but we want to test for both axis so apply the same pattern here
        type: 'log',
      },
      yaxis: {
        title_display_markdown_pattern: "[Data Types](/chaise/recordset/#2/Dashboard:Release_Status)", // link path doesn't make sense but it's just for testing
        tick_display_markdown_pattern: "[{{$self.Data_Type}}](/chaise/recordset/#2/{{$self.Schema_Table}}/::facet::*{{#encodeFacet}}{{$self.Data_Type_Filter}}{{/encodeFacet}}){target=_blank}",
      }
    },
    traces: [{
      uri: "/ermrest/catalog/2/entity/M:=Dashboard:Release_Status/Consortium=GUDMAP/!(%23_Records=0)/$M@sort(ID::desc::)?limit=26",
      legend_disable_default_click: true,
      legend_markdown_pattern: ["[# Released](/chaise/recordset/#2/Dashboard:Release_Status/*::facets::N4IghgdgJiBcDaoDOB7ArgJwMYFM4gGEUJUMAXASzQFsQAaELACxQtyTnhAHEBVAEQCyAQQAKIALoBfaUA)", "[# Created](/chaise/recordset/#2/Dashboard:Release_Status/)"], // links don't make sense since I can't change the facet blob to filter between created/release
      x_col: ["#_Released", "#_Records"],
      y_col: ["Data_Type"],
      graphic_link_pattern: ["/chaise/recordset/#2/{{$self.Schema_Table}}/::facet::*{{#encodeFacet}}{{$self.Data_Type_Filter}}{{/encodeFacet}}"],
      orientation: "h",
      textfont: {
        size: 10
      },
    }],
    plotlyDefaultButtonsToRemove: ["scrollZoom", "zoom2d","sendDataToCloud","autoScale2d", "lasso2d", "select2d", "hoverClosestCartesian", "hoverCompareCartesian", "toggleSpikelines"]
  }]
}

**Comment by DevanshiDesai19** [comment]
Tasks to be performed:

- [ ] CSS styling for links should be made consistent with the one used across the application.

### Bar Graphs:
- [ ]  All the bars, legends , ticks and y-axis labels should be a hyperlink to the specific schema table and it should filter that schema table records with the Data Type filter received from the URI.
- [ ] The X-axis , Y-axis labels and title should redirect to the URL mentioned as a part of the config provided in plot-config.js.

### Pie Chart:


### Histogram:


### Violin Plot:

### Scatter Plot:

### Dot Plot:

### Line Plot:

**Comment by DevanshiDesai19** [comment]
To handle the gudmap-todate-bar chart, we can add the following properties to the plot-config.js:

1.  To add hyperlink to **title** of the plot, add a property **title_hyperlink_pattern** (name can be changed after discussion) 
Location : <plot_name>.plots[i].plotly_config.title_hyperlink_pattern

2. To add hyperlink to **x axis title** of the plot, add a property **title_hyperlink_pattern** (name can be changed after discussion) 
Location : <plot_name>.plots[i].plotly_config.xaxis.title_hyperlink_pattern

3. To add hyperlink to **y axis title** of the plot, add a property **title_hyperlink_pattern** (name can be changed after discussion) 
Location : <plot_name>.plots[i].plotly_config.yaxis.title_hyperlink_pattern.

4. To add hyperlink to the **traces** on the plot i.e. hyperlinks to bars and yaxis ticks, add a hyperlink pattern to the property **y_col_hyperlink_pattern** . (name can be changed after discussion) 
Location: <plot_name>.plots[i].plotly_config.traces[j].y_col_hyperlink_pattern








For instance,


"gudmap-todate-bar": {
      page_title: "GUDMAP Data Status Dashboard",
      // Array of object plots to be shown on the page
      plots: [
          {
              plot_type: "bar",
              config: {
                  format_data_x: true   // defualt : false - to use hack or not
              },
              plotly_config:{
                  title: "Number of GUDMAP resources released to date (log scale)",
                  title_hyperlink_pattern: "?config=gudmap-todate-pie",
                  height: 450,
                  width: 1200,
                  margin: {
                      t: 30,
                      l: 280  // left margin for lengthy data labels.
                  },
                  legend:{
                      traceorder: "reversed"    // order of the legend is reversed
                  },
                  xaxis: {
                      title: "Number of Records",          // plot x_axis label
                      title_hyperlink_pattern: "?config=gudmap-todate-pie",
                      // tickformat: ',d',     // format for the ticks. For more formatting types, see: https://github.com/d3/d3-format/blob/master/README.md#locale_format
                      type: 'log',             // optional value: tickformat should compatible with type

                  },
                  yaxis: {
                      // title: "Data_Types",       // plot y_axis label
                  }
              },
              traces: [
                  {
                      // The request url that has to be used to fetch the data.
                      uri: "/ermrest/catalog/2/entity/M:=Dashboard:Release_Status/Consortium=GUDMAP/!(%23_Released=0)/!(Data_Type=Antibody)/!(Data_Type::regexp::Study%7CExperiment%7CFile)/$M@sort(ID::desc::)?limit=26",
                      legend: ["#_Released"],   // name of traces in legend
                      x_col: ["#_Released"],    // column name to use for x values
                      y_col: ["Data_Type"],                   // array of column names to use for y values
                      orientation: "h",                      // Optional parameter for displaying the bar chart horizontally
                      y_col_hyperlink_pattern: "/chaise/recordset/#2/{{Schema_Table}}/*::facets::{{Data_Type_Filter}}", //For updation 
                      // hovertemplate: ',d',
                      textfont: {
                          size: 10                           // It will work till the bar size can accomodate the font size
                      },
                  },
              ],
              // Plotly defualt buttons/actions to be removed
              plotlyDefaultButtonsToRemove: ["scrollZoom", "zoom2d","sendDataToCloud","autoScale2d", "lasso2d", "select2d", "hoverClosestCartesian", "hoverCompareCartesian", "toggleSpikelines"]
          }
      ]
  },

**Comment by DevanshiDesai19** [comment]
Discussion on how the links needs to be defined:
Initially, we started off by defining simple templating url for the links, then after weighing the pros and cons of simple templating approach vs. markdown templating approach, we saw that the simple templating approach needed usage of multiple variables such as :
titleTemplateVariableNames: [],
titleTextPattern: String,
titleUrlPattern: String,
titleLink: boolean,
titleTargetNewTab: boolean
but the usage of markdown templating gave more flexiblity to define the configuration and less usage of variables needed to configure the link
titleTemplateVariableNames: [],
titleMarkdownPattern: String

So we decided to go forward with markdown templating approach.

The following attributes are added to the configuration file for all the plots according to the discussion with Joshua and Hongsuda:

1. title_markdown_pattern:
   This property is added to the config object to let the user configure the markdown templating pattern to the title of the plot.
   This property is added to the config.xaxis/config.yaxis to let the user configure the markdown templating pattern to the xaxis title and yaxis title of the plot respectively.


2. disable_default_legend_click:
   Initially, we had added this property to allow the user configure the default legend click behaviour irrespective if there is a markdown templating pattern mentioned in the configuration file or not.
   The default behavior of the plotly is that on single click on the legend the traces or the bars associated with legend disappears and the pie or the bar is configured with the data of the remaining legends.
The default behaviour of plotly plots is that on double click on legend the bar or the pie chart with be refreshed to contain only that trace or bar.
More on this can be seen here: https://codepen.io/plotly/pen/vazxKv

  After adding the markdown pattern on the legends we realized that if the default legend click events were not disabled and there was a markdown pattern on the legend then it looked very confusing to the user.
So after discussion, we decided that if there was a markdown pattern defined for legends then the default legend click events will be disabled.

3. legend_markdown_pattern(For Pie chart):
 This is a markdown templating pattern and it will be used to provide links to the legend labels. 
Initially adding markdown pattern link to the legend labels were also inserting links in the tooltip on the plots. For this we introduced a new variable text which needs to be sent to the plotly app which will not hyperlink the text in the tooltip.
Post that, according to my understanding, to make the legend as a hyperlink we have added markdown pattern which has <a> tag in it. Then on legend_click event we are opening that url in a separate window.

**Comment by DevanshiDesai19** [comment]
I have raised a pull request:  https://github.com/informatics-isi-edu/deriva-webapps/pull/117/files/135ec6bb41d4bc23490a8bb69ebab2973c9ddc1b
with some comments.

This can be used in conjunction with the following configuration:

"gudmap-todate-pie-v3": {
    page_title: "GUDMAP Release Status Dashboard",
    // Array of object plots to be shown on the page
    plots: [
        {
            plot_title: "Number of GUDMAP resources released to-date",
            // ValuesValues can be from : "line", "bar", "dot", "area", "dot-lines", "pie", "histogram-horizontal", "histogram-verical"
            plot_type: "pie",
              plotly:{
                  layout: {
                    showlegend: true,  // ##DD : Was added as a part of config object but should be a part of layout object        
                  }
              },
              config:{
                title_hyperlink_pattern: "[{{Title}}](https://dev.isrd.isi.edu/chaise/search{{Context_Params}}){target=_blank}",
                slice_label: "value",     // ##DD: Not relevant to plotly config.Used for configuring value in file.so added in plotly_config.
                format_data: true,         // ##DD: Not relevant to plotly config.Used for configuring value in file.so added in plotly_config.
                disable_default_legend_click: true
              },
            traces: [
                {
                    // The request url that has to be used to fetch the data.
                    uri: "/ermrest/catalog/2/entity/M:=Dashboard:Release_Status/Consortium=GUDMAP/!(%23_Released=0)/!(Data_Type=Antibody)/!(Data_Type::regexp::Study%7CExperiment%7CFile)/$M@sort(ID::desc::)?limit=26",
                    // legend: ["Browser All Events 1","Browser All Events 2"],   // name of traces in legend
                    data_col: "#_Released",     // name of the attribute of the data column
                    legend_col: "Data_Type",     // name of the attribute of the legend column
                    show_percentage: false,     // to show the percentage or not on slices
                    legend_markdown_pattern:"[{{Title}}](/chaise/recordset/#2/{{Schema_Table}}/*::facets::{{Data_Type_Filter}}){target=_blank}",
                }
            ],
            // Plotly defualt buttons/actions to be removed
            plotlyDefaultButtonsToRemove: ["scrollZoom", "zoom2d","sendDataToCloud","autoScale2d", "lasso2d", "select2d", "hoverClosestCartesian", "hoverCompareCartesian", "toggleSpikelines", "hoverClosestPie"]
        }
    ]
},

**Comment by DevanshiDesai19** [comment]
Post todays discussion with Joshua, I understood that I had written redundant code by adding the link twice in the code, once on legend_click event and once by adding markdown pattern in configuration file. Made the relevant changes.

**Comment by DevanshiDesai19** [comment]
Tasks still pending:
-[ ] plot_title needs to be moved to plotly.config object
-[ ] template variables needs to be added to let the user configure the markdown pattern

**Comment by DevanshiDesai19** [comment]
As the hyperlinks for legends are mentioned in as markdown templating pattern like this:

                    **legend_markdown_pattern:"[{{Title}}] (/chaise/recordset/#2/{{Schema_Table}}/*::facets::{{Data_Type_Filter}}) {target=_blank}",**

The link mentioned in the markdown pattern must be a valid relative or full url link as in the code we are trying to match that link with valid regex pattern : /<a\b.+href="([^\n\r]*)"\s/ig (this regex is used in the chaise codebase to match and fetch the link.

**Comment by DevanshiDesai19** [comment]
{
  // Parameters that need to be sent to the plotly used for configuring the plot.
  plotly: {
    config: { ... },
    layout: { ... },
    ...
  }, 
 // Parameters used in the code to change the default/configured parameters that need to be sent to plotly.
  config: {

    // title_markdown_pattern is a markdown pattern which modifies the title of the plot to be made clickable
    title_markdown_pattern: "", (Markdown pattern format: [{{Title}}]( _FULL/RELATIVE URL_ {{Context_Params}}){target=_blank} )

    // title_template_variables are key value pairs which are used for replacing the templating variables in the title markdown pattern.
    title_template_variables: {},

    xaxis: {
     // title_markdown_pattern under xaxis is a markdown pattern which modifies the xaxis title of the plot to be made clickable
      title_markdown_pattern: "", (Markdown pattern format: [{{Title}}]( _FULL/RELATIVE URL_ {{Context_Params}}){target=_blank} )

      // title_template_variables are key value pairs which are used for replacing the templating variables in the xaxis title markdown pattern.
      title_template_variables: {},

      ...

      // tick_markdown_pattern under xaxis is a markdown pattern which modifies the ticks on xaxis to be clickable
      tick_markdown_pattern: "", (Markdown pattern format: [{{Title}}]( _FULL/RELATIVE URL_ {{Context_Params}}){target=_blank} )

      // tick_template_variables are key value pairs which are used for replacing the templating variables in the xaxis tick markdown pattern.
      tick_template_variables: {}

    },
    yaxis: {

     // title_markdown_pattern under yaxis is a markdown pattern which modifies the yaxis title of the plot to be made clickable
      title_markdown_pattern: "", (Markdown pattern format: [{{Title}}]( _FULL/RELATIVE URL_ {{Context_Params}}){target=_blank} )


      // title_template_variables are key value pairs which are used for replacing the templating variables in the yaxis title markdown pattern.
      title_template_variables: {},
      ...

     // tick_markdown_pattern under Yaxis is a markdown pattern which modifies the ticks on Yaxis to be clickable
      tick_markdown_pattern: "", (Markdown pattern format: [{{Title}}]( _FULL/RELATIVE URL_ {{Context_Params}}){target=_blank} )

      // tick_template_variables are key value pairs which are used for replacing the templating variables in the yaxis tick markdown pattern.
      tick_template_variables: {}
    }
  },
  traces: [{
    uri: ...,
    data_col: "",
    legend_col: "",
    show_percentage:""

    // legend_markdown_pattern is a markdown pattern which modifies the legends to make it clickable.
    legend_markdown_pattern: "",  (Markdown pattern format: [{{Title}}]( _FULL/RELATIVE URL_ {{Context_Params}}){target=_blank} )

    // legend_template_variables is a key value pair which can be used for replacing the templating variables in legend markdown pattern.
    legend_template_variables: {},

    // disable_default_legend_click is a flag which enables or disables the default legend click event(built in plotly event).
   // This can only be configured if the legend markdown pattern is not defined.
    disable_default_legend_click: true | false
  }, ...
  ]
}




To elaborate more on how we need to configure title_template_variables, it can be defined in the following fashion:
title: "Number of GUDMAP resources released to-date"
title_markdown_pattern : "[{{Title}}](/chaise/recordset/#2/{{Schema_Table}}){target=_blank}",
title_template_variables : {  "Schema_Table" : "Protocol" }


Since title_markdown_pattern and title_template_variables have one to one mapping and hence configuring it can be done easily.
But, it is different in the case of legend_template_variables as the variables change for each trace, for instance, the configuration needs to be defined: 
traces:[
       uri: "/ermrest/catalog/2/entity/M:=Dashboard:Release_Status/Consortium=GUDMAP/!(%23_Released=0)/!(Data_Type=Antibody)/!(Data_Type::regexp::Study%7CExperiment%7CFile)/$M@sort(ID::desc::)?limit=26",
       data_col:"#_Released",
       legend_col: "Data_Type",
       legend_markdown_pattern : "[{{Title}}](/chaise/recordset/#2/{{Schema_Table}}/*::facets::{{Data_Type_Filter}}){target=_blank}",
       legend_template_variables : {
              // need to discuss how we want to configure this
       }
]


Currently in the code, we mention the template variables to be sent for templating in following fashion,
For each row of data recieved from the URI,
                                                                $rootScope.templateParams= {
                                                                    Schema_Table: row['Schema_Table'],
                                                                    Data_Type_Filter: ERMrest.encodeFacet(row['Data_Type_Filter']),
                                                                };

**Comment by DevanshiDesai19** [comment]
Snippet from one of the conversation with Joshua: 
 
if ERMrest.renderMarkdown() fails, it should be returning null rather than an error. If this is the case (which it will be sometimes), we should have a “catch” for when the template returns null and provide a fallback (and maybe output something in the console)

**Comment by DevanshiDesai19** [comment]
With reference to the comment I had said yesterday, when I researched more about it today, I understood that to show the legend label as hyperlink(Blue coloured text) we need to wrap it around with the anchor tag and then use window.open() explicitly on plotly_legendclick function callback.

I found this https://codepen.io/etpinard/pen/yamvBM code snippet which mentions the same thing.

Appologies for not mentioning it beforehand..

We need to review it again if we want to go forward with markdown pattern in legend_markdown_pattern.

In my view, it is better to have markdown pattern with the window.open() function mentioned in plotly_legendclick function because this will ensure that all links have the same colour on hover,active and visited (consistent with all links in chaise). Also the code pen example that I found on internet is also doing the same thing.

**Comment by jrchudy** [comment]
In plot app, we want to follow something similar to what we did in ermrestJS since the data to populate the plot will always be returned from each trace.uri. We will want to add this structure to the template variables object:
```
templateVariables: {
  "$traces": [
    { values: [] },
    ...
  ]
```
This will allow the data modeler to access the data from any trace (or do some aggregate across all traces).

We also want to consider the other case for when we are operating within a trace. In the trace object, we have values that refer to the value of a column returned in the data request when figuring out the content “per row”. So in some cases, the data modeler might want to refer to the data from this specific trace’s uri using `$self`:
```
templateVariables: {
  "$traces": [
    { values: [] },
    ...
  ],
  "$self": { values: [] } // the same as traces[current]
```

**Comment by DevanshiDesai19** [comment]
As per the discussion with Joshua, we are adding hovertemplate_display_pattern property to the pie chart as it will allow the user to modify the text inside the tooltip.

We decided to not add hovertemplate_markdown_pattern pattern as a link on tooltip is pointless since individual traces are clickable.

**Comment by DevanshiDesai19** [comment]
For Tracking purpose:

- [ ] Pie:
  - [ ] title_display_markdown_pattern
  - [ ] xaxis.title_display_markdown_pattern
  - [ ] yaxis.title_display_markdown_pattern
  - [ ] graphic_link_pattern
  - [ ] disable_default_legend_click
  - [ ] hovertemplate_display_pattern
  - [ ] tick_display_markdown_pattern
  - [ ] legend_markdown_pattern

- [ ] Bar:
  - [ ] title_display_markdown_pattern
  - [ ] xaxis.title_display_markdown_pattern
  - [ ] yaxis.title_display_markdown_pattern
  - [ ] graphic_link_pattern
  - [ ] disable_default_legend_click
  - [ ] hovertemplate_display_pattern
  - [ ] tick_display_markdown_pattern
  - [ ] legend_markdown_pattern

- [ ] Violin:
  - [ ] title_display_markdown_pattern
  - [ ] xaxis.title_display_markdown_pattern
  - [ ] yaxis.title_display_markdown_pattern
  - [ ] graphic_link_pattern
  - [ ] disable_default_legend_click
  - [ ] hovertemplate_display_pattern
  - [ ] tick_display_markdown_pattern
  - [ ] legend_markdown_pattern

- [ ] Dot:
  - [ ] title_display_markdown_pattern
  - [ ] xaxis.title_display_markdown_pattern
  - [ ] yaxis.title_display_markdown_pattern
  - [ ] graphic_link_pattern
  - [ ] disable_default_legend_click
  - [ ] hovertemplate_display_pattern
  - [ ] tick_display_markdown_pattern
  - [ ] legend_markdown_pattern

- [ ] Histogram:
  - [ ] title_display_markdown_pattern
  - [ ] xaxis.title_display_markdown_pattern
  - [ ] yaxis.title_display_markdown_pattern
  - [ ] graphic_link_pattern
  - [ ] disable_default_legend_click
  - [ ] hovertemplate_display_pattern
  - [ ] tick_display_markdown_pattern
  - [ ] legend_markdown_pattern

**Comment by DevanshiDesai19** [comment]
Change the cursor to pointer:
Reference link: https://developer.mozilla.org/en-US/docs/Web/CSS/cursor
https://codepen.io/destrada/pen/perVON
https://community.plotly.com/t/cursor-pointer-style/2237

**Comment by DevanshiDesai19** [comment]
For the Grouped Bar Chart,
As far as I researched, I found out that there is no way to detect which one of the n bars on the bar chart were clicked, so providing an array of graphic_clickable_links will not allow the user to identify which of the bar was clicked and navigate to the particular link.

Referred to one of the following URL for stacked bar chart where the user has used a workaround to detect the click on the colour on which the click was made:
https://codepen.io/etpinard/pen/ZWwqoy

I also tried to compare the data object which is received on click event of the each coloured bar.
 ![image.png](https://images.zenhubusercontent.com/60a44fefacdb8bfa888e15e5/3bad12e8-1f1b-44fc-8d86-265421738221)

When a click event takes place on Antibody[Created] (Orange bar):
![image.png](https://images.zenhubusercontent.com/60a44fefacdb8bfa888e15e5/0dbad76c-63b0-41c8-bcce-d70675b56b67)


When a click event takes place on Antibody[Released] (Blue bar):
![image.png](https://images.zenhubusercontent.com/60a44fefacdb8bfa888e15e5/50adbae7-5fc9-42f1-9c9f-a9735014fc9b)

**Comment by DevanshiDesai19** [comment]
According to the discussion, the graphic_link_pattern can be provided as a string or as an array of size 1 as it is implemented in chaise.
Changes for this has been added

**Comment by DevanshiDesai19** [comment]
Discussion regarding Violin Plot:

The legend_link_pattern and graphic_link_pattern are implemented in a different way than all the other graphs as it has dropdown included in it. So instead of including both these attributes in traces object, we are including these attributes as a part of groupkey:
 group_keys: [
                        {
                            column_name: "Experiment",
                            title_display_pattern: "Experiment",
                            title_display_markdown_pattern : "[Experiment](/deriva-webapps/plot/?config=gudmap-todate-bar){target=_blank}",
                            //tick_display_pattern: "{{{$row.Experiment}}}: {{{$row.Experiment_Internal_ID}}}",  // NOTE: this templates the value based on $row (response.data[index]) being in template environment
                            tick_display_markdown_pattern: "[{{{$row.Experiment}}}: {{{$row.Experiment_Internal_ID}}}](/deriva-webapps/plot/?config=gudmap-todate-pie)",  // NOTE: this templates the value based on $row (response.data[index]) being in template environment
                            default: true,
                            graphic_link_pattern:["/chaise/recordset/#2/RNASeq:Replicate_Expression@sort(ID)"],
                            legend_markdown_pattern:["[{{{ value }}}](/chaise/recordset/#2/RNASeq:Replicate_Expression)"]
                        },
                        {
                            column_name: "Anatomical_Source",
                            title_display_pattern: "Anatomical Source",
                            title_display_markdown_pattern : "[Anatomical Source](/deriva-webapps/plot/?config=gudmap-todate-bar){target=_blank}",
                            tick_display_markdown_pattern: "[prostate gland](/deriva-webapps/plot/?config=gudmap-todate-pie)",  // NOTE: this templates the value based on $row (response.data[index]) being in template environment
                            graphic_link_pattern:["/deriva-webapps/plot/?config=gudmap-todate-pie"],
                            legend_markdown_pattern:["[{{{ value }}}](/chaise/recordset/#2/RNASeq:Replicate_Expression)"]
                        }, {
                            column_name: "Experiment_Internal_ID",
                            title_display_pattern: "Experiment ID"
                        }, {
                            column_name: "Replicate",
                            title_display_pattern: "Replicate"
                        }, {
                            column_name: "Sex",
                            title_display_pattern: "Sex"
                        }, {
                            column_name: "Species",
                            title_display_pattern: "Species"
                        }, {
                            column_name: "Specimen",
                            title_display_pattern: "Specimen"
                        }, {
                            column_name: "Specimen_Type",
                            title_display_pattern: "Specimen Type"
                        }, {
                            column_name: "Stage",
                            title_display_pattern: "Stage"
                        },
                    ],
                    default_all_studies_group: "Anatomical_Source"
                },

**Comment by jrchudy** [comment]
Tasks left to complete include:
 - hovertemplate_display_pattern for all graph types
 - legend_markdown_pattern for `histogram` and `dot`
 - graphic_link_pattern for `dot`
