### ISSUE TITLE
Proper logging support

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/deriva-webapps#109]
Looking at the current implementation of deriva webapps, some of them are not properly utilizing the logging mechanism that we have in Chaise. The following are the required changes to achieve this:

> Before explaining, I (Aref) should mention that I wrote this based on my understanding of the apps. And also some apps are totally different than the rest. If what I said doesn't apply to an app or might sound incorrect/inaccurate, let us know. @jrchudy Since you're more experienced with deriva webapps, I think you should go through what I added and edit/provide more info. Any where that I wasn't sure I added mentioned you so please provide more info there.

> We might want to rearrange this. I didn't write this based on how I think @DevanshiDesai19 should work on it.

### 1. Make sure wid, pid, cid are set

These three attribute are the bare minimum for logging. And their values should be set on page load and all the requests after it should use the same values. 

- If a deriva webapp is using the [config app method](https://github.com/informatics-isi-edu/chaise/blob/master/docs/dev-docs/config-app.md) then you don't need to make any changes and `chaise.config` module handles this. 
- Otherwise you would have to make sure there are global values for `cid`, `pid`, `wid`.
- If an app is using Reference API, the first thing that it does is `ERMrest.resolve`. This function will "introspect" the model. It will also create an internal "server" object which will be used for any subsequent request sent using the Reference API. So you would have to make sure the general attributes (`cid`, `pid`, `wid`) are passed with resolve. You can see an example of it [here](https://github.com/informatics-isi-edu/deriva-webapps/blob/master/plot/plot.app.js#L340) and [here](https://github.com/informatics-isi-edu/deriva-webapps/blob/master/heatmap/heatmap.js#L44).

### 2. (previously 4) Consume `pcid` and `ppid` that might be in the url 

As you can see in the logging document, `ppid` and `pcid` are logged alongside the "main request" of each app. We should do the same thing here. Which is,
- Extract the `pcid` and `ppid` query parameter values. You can use the [`UriUtils. getQueryParams`](https://github.com/informatics-isi-edu/chaise/blob/master/common/utils.js#L1022) function for that purpose. You can see how the singular version of this function is used [here in plot app](https://github.com/informatics-isi-edu/deriva-webapps/blob/master/plot/plot.app.js#L1130).
-  Depending on how fragile each app is, adding query parameter might break them. So you might have to make some modifications to how each app is consuming url as well.
- We need to identify which request in the app is considered the main one. Based on my understanding, most of them are sending just one request. Assuming we know which request it is, we have to make sure that request is also sending `pcid` and `ppid`.

### 3. Provide other attributes depending on the request

Each request to server must send proper log attributes (context header),

- If an app is using Reference API and therefore it has `.read` calls, the second parameter is log object. You have to make sure at least the following are defined in there:
  - `action`: A string explaining what the request is about. @jrchudy you or Devanshi should list the requests that apps are sending and we can go over what should we use for action string. This can be done by just going through the code and finding the `read` or `.get` requests.
     - apps/requests without actions will be handled in task 5 listed below
  - `schema_table`: The schema and table names in "schema:table" format.
     - for each request being sent to fetch data, we want to parse the request url and use the schema_table combination specific to that request
  - `catalog`: The catalog number.
    - for each request being sent to fetch data, we want to parse the request url and use the catalog id specific to that request
  - `stack`: You can ignore this for now. This requires more thought!
- Otherwise we should make sure a `headers` object with proper key name is passed. It should have the same attributes that I explained in the previous bullet. You can find an example of it [here](https://github.com/informatics-isi-edu/deriva-webapps/blob/master/boolean-search/booleansearch.app.js#L117,L121)

### 4. Add pcid query parameter to links to Chaise

In each app, there might be links to other deriva-webapps or chaise apps. We should make sure all these links include `pcid` and `ppid` query parameters. You can find an example of this in [boolean-search](https://github.com/informatics-isi-edu/deriva-webapps/blob/master/boolean-search/booleansearch.app.js#L462). For `pcid` you should use the `appName` constant that is defined for each app. If it's not defined (since it's not an AngularJS app), you can just hard code it. I think that's how treeview is doing it. 

Josh: For treeview, the values are being set at the beginning of the app and reused each time `getHeader` is called. When creating links for treeview app to navigate to chaise pages, `pcid` should use this defined `cid` from above.

### 5. Add actions and properly logging to Plot app

In Plot app, for the violin plot type, we currently create 2 different references for fetching data for the selectors and then there's an http.get request to fetch the data for the plot. These 3 data requests need to have actions defined for them since they currently don't have a defined action. The 2 selector requests do use the `contextHeaderParams`, but need to be checked for accuracy.

For all of the other plot types, there is a single http.get request being sent to fetch the data with no context headers defined. This case needs context headers and a defined action.

**Comment by jrchudy** [comment]
Boolean-search
1.
2.
3.
4.

Heatmap
1.
2.
3.
4.

Lineplot
Which task to complete still
1.
2.
3.
4.

Plot
1.
2.
3.
4.

Treeview
1.
2.
3.
4.

**Comment by DevanshiDesai19** [comment]
The list of requests which need defination for schema_table and action are as follows:

1. Line Plot:
a. Main request: 
- [ ] Schema_table: 
- [ ] Action: 

2. Plot App:
a. Specific to Violin Plot:
- [ ] Schema_table:
- [ ] Action

b. For all other plots(bar,pie..):
-[ ] Schema_table:
- [ ] Action:


As discussed, incorporation of the stack attribute is not done as a part of this issue

**Comment by jrchudy** [comment]
Created issue #115 to track the remaining tasks from this issue (task 5 above). The actions for plot app are defined in the action list document and will be handled in that issue.

Tasks 1-4 are complete and merged into master.
