### ISSUE TITLE
Dashboard display error on rbk-dev gudmap homepage

### ISSUE THREAD

**Issue by ljpearlman** [informatics-isi-edu/deriva-webapps#116]
The dashboard iframe in https://dev.gudmap.org gives this error:

> 400 Bad Request The request is malformed. URL parse error at token: LexToken(@,'@',1,160) You may need to login to see the model or data. Please login to continue

The failing ermrest request is https://dev.gudmap.org/ermrest/catalog/2/entity/M:=Dashboard:Release_Status/Consortium=GUDMAP/!(%23_Released=0)/!(Data_Type=Antibody)/!(Data_Type::regexp::Study%7CExperiment%7CFile)/@sort(ID::desc::)?limit=26

which I'm guessing should be the same thing without the `/` before the `@`:

https://dev.gudmap.org/ermrest/catalog/2/entity/M:=Dashboard:Release_Status/Consortium=GUDMAP/!(%23_Released=0)/!(Data_Type=Antibody)/!(Data_Type::regexp::Study%7CExperiment%7CFile)@sort(ID::desc::)?limit=26

I'm not sure whether this is a config error or a problem with the plot app itself.

**Comment by jrchudy** [comment]
Looks like this has been fixed on dev.gudmap.org. The plot-config in division repo for dev/staging/production show a fix for this. 

https://github.com/informatics-isi-edu/division/blob/master/kvm/rbk-dev/www/deriva-webapps/plot/plot-config.js#L213
