### ISSUE TITLE
Plot app: failed attempts to delete annotations sometimes spin forever

### ISSUE THREAD

**Issue by ljpearlman** [informatics-isi-edu/deriva-webapps#125]
On facebase, the Image_Annotation table has a static acl that results in "null" update and delete permissions for the facebase-writers group, and a dynamic acl that gives update and delete permissions to the project-specific group associated with each record.

If a user in the facebase-writers group but not in the project-specific group associated with a record brings up the plot app on the associated image, then they'll see the update icon next to the annotation; if they click on that, they'll see the trash can icon, and if they click on that, the app will attempt to delete the Image_Annotation record, and that attempt will fail with a 403. All this is correct behavior. The problem is that instead of producing an error message after the failure, the app just shows the "saving changes" spinner forever.

If you need to be set up with permissions to test this out on facebase, @bugacov can help.

**Comment by RFSH** [comment]
With the recent changes in Chaise, viewer app will now properly look for dynamic ACLs to show/hide the delete and edit buttons. So you should not be able to see the delete button in this scenario anymore. 

I tested this on Facebase and it's working as expected now. So I'm going to close this issue. Please feel free to create new issue in Chaise repo for viewer-related issues.
