### ISSUE TITLE
Matrix search bar is cutting content in Safari

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/deriva-webapps#133]
On Safari 16.3. when you first load the page, and type a search (e.g., "mandible") at some point while typing the word, the text in the search box starts to scroll to the left as if there wasn't enough room in the search box control for the text. 

This is only happening on the first search attempt and after that the search box properly adjusts the content. It's also not reproducible in Firefox or Chrome. 

<img width="1445" alt="Screen Shot 2023-02-24 at 11 29 22 AM" src="https://user-images.githubusercontent.com/2129750/221277903-f2a18b0c-f254-4d65-b237-2e98d2b12553.png">

**Comment by cheekw** [comment]
I did a quick test on safari too but I'm unable to reproduce the issue.

**Comment by RFSH** [comment]
@cheekw Did you test the latest version on `master` branch? or the one that you had before? To make this look similar to Facebase I moved the searchbox to the left (like you can see in the screenshot) and that might have made this worse.
