### ISSUE TITLE
Show matrix rows in a treelike view

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/deriva-webapps#145]
The current matrix app allows us to show the different `z` values for a combination of `x` and `y` values. It will show the `x` or `y` values in a flat list. 

In this issue, we want to explore the possibility of showing a hierarchal dependency of `y` values in the same view. This essentially means combining the treeview app and matrix. I only mentioned `y` because we already have a UI solution for showing a vertical tree (tree view app), but a horizontal one might not be as straightforward.

_This description is subject to change and is not finalized. I created this issue so we can keep the discussion about this feature in one place._

**Comment by RFSH** [comment]
When we build ermrestjs, chaise, or deriva-webapps, a new `dist` folder is created. We then deploy this folder into a desired location (either remote or local).

Since this is an experimental feature, we want to avoid deploying it on the server and want to be able to test it locally. So we only want to build the files and skip deploying the code to another location. 

In the following, I will write step-by-step instructions on how to achieve this:

1. Ensure [Node.js](https://nodejs.org/en/) is installed on your machine. I recommend installing it with [nvm](https://github.com/nvm-sh/nvm), allowing you to switch between different versions easily.

2. You need to create a parent folder that, in the end, we can serve. All the repositories you will clone must have the same parent folder and are siblings. In my case, I created a folder called "isi":

    ```sh
    mkdir isi
    cd isi
    ``` 

3. Let's continue by cloning ermrestjs and deriva-webapps in this folder:

    ```sh
    git clone git@github.com:informatics-isi-edu/ermrestjs.git
    git clone git@github.com:informatics-isi-edu/deriva-webapps.git
    ```
4. Our build process can be customized by defining environment variables. The following is how you should define them for this local installation: 

    ```sh
    export WEB_URL_ROOT=./../
    export WEBAPPS_REL_PATH=
    export ERMRESTJS_REL_PATH=../../../ermrestjs/dist/
    export CHAISE_REL_PATH=../../../chaise/dist/
    ```

5. Use `echo` command to make sure these variables are correct, so

    ```sh
    echo $WEB_URL_ROOT
    echo $WEB_INSTALL_ROOT
    echo $ERMRESTJS_REL_PATH
    echo $CHAISE_REL_PATH
    ```
    This should print the defined values, not `/var/www/html` paths or empty values.

6. Build ermrestjs:
    
    ```sh
     cd ermrestjs
     make dist
     ```
     If this step was successful, you should see a `dist` folder under `ermrestjs` folder.


7. The previous steps are only needed for the initial setup, and you don't need to repeat them when implementing deriva-webapps features. So now let's go to the deriva-webapps folder and switch to the proper branch:

    ```sh
    cd ../deriva-webapps
    git checkout matrix-treeview
    ```

8. In this branch, I made the initial changes to make the matrix app work locally. In the `local-test` folder, you can find the following files:

    - `matrix-config.js`: The configuration file that matrix uses for finding where the data are and other customization. [Here](https://github.com/informatics-isi-edu/deriva-webapps/blob/master/config/matrix-config-sample.js) is the equivalent version on the main branch. You can see how we're using relative paths instead of referring to `/ermrest/`.
    - `x_values.json`, `y_values.json`, `z_values.json`, `x_y_z_values.json`: The data files.

9. While you can build deriva-webapps with the same `make dist` command as ermrestjs, it will always reinstall npm packages. While developing features, I would like to skip this step. That's why I directly install the dependencies and then use an alternative command to skip the reinstallation of npm packages. So run the following to install all the Chaise dependencies:
    
    ```sh
    make npm-install-all-modules
    ```

10. (optional) Properly define `NODE_ENV` depending on whether you want to install in "development" mode or "production":

    ```sh
    export NODE_ENV="production"
    ```
    - Use "production" mode by default. Use "development" mode only when you want to debug.
    - If this environment variable is not defined, it will default to "production" mode.

11. Build the matrix app:

    ```sh
    make dist-wo-deps
    ```
    If this step was successful, you should see a `dist` folder under `deriva-webapps` folder.


12. You can now access the matrix app by opening the `deriva-webapps/dist/react/matrix/index.html` file in a browser. But this will give you a CORS error while fetching the data. To solve this, you should solve the parent `isi` folder we created. The simplest way to achieve this is using the [Live Server extension](https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer) of [VS code](https://code.visualstudio.com/). I highly recommend using VSCode for development in general. For this, follow the following steps:
    1. Install [VS Code](https://code.visualstudio.com/).
    2. Install [Live server extension](https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer)
    3. Open the `isi` folder in VS Code. I recommend creating a workspace based on this folder.
    4. You will see a "Go Live" button on the bottom right of VS Code. Click on it.
    5. It will open a browser and shows the content of `isi` folder. Navigate to `deriva-webapps/dist/react/matrix`
    6. You should see the matrix app properly loaded.

**Comment by jrchudy** [comment]
I added `y_values_tree.json` with an example row of how data might relate in parent/child relationships. This should be expanded to have more rows to make the tree structure more complex. A similar file should be created for the x axis when working on the horizontal tree.

This is a link to the functions used to consume the relationship data and create the tree from it in the treeview app:
https://github.com/informatics-isi-edu/deriva-webapps/blob/master/treeview/js/main.js#L692-L987

**Comment by JunmengXu** [comment]
Thank you, this is very helpful. I will look at it

**Comment by JunmengXu** [comment]
To extend the function, I explored different plug-ins and filtered the appropriate ones by comparing the UI extensibility and applicability to the project requirements, as well as browser compatibility and other features. Details can be found in the [Hierarchy Plug-ins doc](https://docs.google.com/document/d/1YOHM-yhrqCWokXXwGXKYV9CBItqvk8MIK-LD0CF4TXo/edit?usp=sharing).

Through [test cases](https://docs.google.com/document/d/1rBfn-gG1E8D35JKJTQ28DzeafYrmlmHkoNc_mnMQmxQ/edit?usp=sharing) for AntV, MUI, and rc-tree which are in the positive list. MUI gives us more customization for the style of trees than AntV, and more built-in functions than rc-tree.

So I choose MUI as the tree component to dig in and begin introducing it to the matrix app.
