### ISSUE TITLE
Image gallery app

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/deriva-webapps#15]
As an example: https://research.cchmc.org/lungimage/?p=20740

**Comment by carlkesselman** [comment]
You know this is Bruce’s college right?  This is lungMAP

Carl

Sent from my iPad

----------------------------------------------------------
Dr. Carl Kesselman
Dean’s Professor, Epstein Department of Industrial and Systems Engineering
Fellow, Information Sciences Institute
Viterbi School of Engineering

Professor, Preventive Medicine
Keck School of Medicine

University of Southern California
4676 Admiralty Way, Suite 1001, Marina del Rey, CA <x-apple-data-detectors://1/0>  90292-6695<x-apple-data-detectors://1/0>
Phone:  +1 (310) 448-9338<tel:+1%20(310)%20448-9338>
Email:  carl@isi.edu<mailto:carl@isi.edu>
Web: http://www.isi.edu/~carl


On Nov 1, 2018, at 8:32 PM, Hongsuda <notifications@github.com<mailto:notifications@github.com>> wrote:


As an example: https://research.cchmc.org/lungimage/?p=20740

**Comment by hongsudt** [comment]
Yes. I came across the presentation style while browsing.  Upon closer investigation, it is wordpress..  Josh has found some alternatives that we might be able to use.


________________________________

**Comment by jrchudy** [comment]
We have something similar implemented in the viewer app in chaise folder.

**Comment by hongsudt** [comment]
No, we don't. We have a multi-z browser which is similar but not the same
as image gallery. The UI will have to be different..

**Comment by RFSH** [comment]
Moved to wishlist.
