### ISSUE TITLE
Plot app: Backwards Compatibility Issue with Deprecated Syntax (plotly_config) in Config File

### ISSUE THREAD

**Issue by KenyShah24** [informatics-isi-edu/deriva-webapps#159]
The current implementation of our system could face backwards compatibility issue related to deprecated syntax in the config file. For example, `gudmap-data-summary-responsive` plot-type is using `plotly_config: {}`:
```
'gudmap-data-summary-responsive': {
    headTitle: 'GUDMAP Data Summary Dashboard',
    // Array of object plots to be shown on the page
    plots: [
      {
        plot_type: 'bar',
        config: {
          format_data_x: true, // defualt : false - to use hack or not
        },
        plotly_config: {
          ...
        },
        traces: [
          {
           ...
          },
        ],
        // Plotly defualt buttons/actions to be removed
        plotlyDefaultButtonsToRemove: [
          ...
        ],
      },
    ],
  },
```

We have two potential courses of action to address this problem:
1. Fix backwards compatibility: We can make the necessary adjustments to ensure that the deprecated syntax works as expected. This solution would allow us to maintain compatibility with existing configurations.
2. Remove old syntax and use the new one instead:  It appears that most examples in our deployments already utilize the `plotly.layout` syntax, so adopting the new syntax could potentially provide a simple solution to the issue.

**Comment by jrchudy** [comment]
Configuration documents:
 - atlas-d2k dev - https://github.com/informatics-isi-edu/division/blob/master/kvm/atlas-d2k-dev/www/deriva-webapps/config/plot-config.js
 - rbk dev - https://github.com/informatics-isi-edu/division/blob/master/kvm/rbk-dev/www/deriva-webapps/config/plot-config.js
 - facebase dev - https://github.com/informatics-isi-edu/division/blob/master/kvm/facebase-dev/www/deriva-webapps/plots/plot-config.js

**Comment by jrchudy** [comment]
This has been fixed in the configuration documents on the servers.
