### ISSUE TITLE
Allow for plot data to come from a file

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/deriva-webapps#162]
We want to be able to fetch plot data from a file instead of ermrest. The use case mentioned said the file content would be CSV. We want to be able to fetch data from any API (not just ermrest) as json or csv, as well as from a file from any url that is json or csv. The following needs to be done to support this:
 - change `queryPattern` to be `url_pattern`
   - determine if there is a host or domain name in the url_pattern (dev.gudmap.org)
   - if there is no host/domain name, assume same host
 - add another property to `traces` to communicate the expected format the data is in
   - lets call this `response_format` (similar to the accept header)
     - this property should accept 'csv' | 'json' only
     - **what content types in `response.headers.content-type` do we want to match against?**
   - this property is optional
   - if not defined, try to figure out the type of the content returned (json or csv)
     - if we can't figure out type, assume json
     - **if something goes wrong because we assumed json, throw error? warning? or show "No Data"?**
 - Create a `.json` file and `.csv` file in your user directory on dev.gudmap
   - pick a plot config to test this for and copy the contents of the response into a `.json` file
   - to test loading data from ermrest as csv, append `?accept=csv` as a query parameter to the `queryPattern` (now url_pattern)
     - copy these contents into a `.csv` file
 - make changes in code to parse csv data properly into a json structure similar to what we've been working with from ermrest

**Comment by KenyShah24** [comment]
For parsing CSV file we can either use the library or internal parser written within the code:

1. fast-csv: [@fast-csv/format] and [@fast-csv/parse] => We need only parser 
 **- Slow as compared to other parsers**
 - size: 8.75kb
3. react-papaparse:  easy to use, just Papa.parse(input, config), very fast, Can parse strings, local files, and even download remote files
, Fast mode for non-quoted data
, Streaming support for parsing large files, Automatic type conversion

, compliant and correctly handles line-breaks and quotations

 **- Has many such functionalities which we don't need causing an unwanted increase in the package size**
 - size: 71kb
4. csv-parse: Flexible with lot of options, works on big datasets,
 **- size 1.38MB**
5. csv-parser: lightest parser
 - size: 1.5kb
If we are only gonna have specific types of csv and we will always know it's format it's better to use the parser created in the code itself. That will be simpler. But if the csv files are out of our control and has many edge cases like having no header, all or some fields wrapped in quotes, linebreaks in quotes,etc then using library will be better.

**Comment by KenyShah24** [comment]
- Using react-papaparse for parsing csv file as csv-parser and fast-csv are used for node JS and are not supposed to use for browser-based parsing.
- **if something goes wrong because we assumed json, throw error? warning? or show "No Data"?** : In this case a warning pop up will be shown with **No Data** for plot.
- **If `response_format` doesn't match with the type of the file passed in the url_pattern then a warning popup will be shown and data if valid will be parsed according to it's type**
