### ISSUE TITLE
Update README links

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/deriva-webapps#185]
After the recent changes to gudmap/atlas-d2k config changes most of the plot links in the README.md are broken. We should update these and if we don't have any example link for them we should just remove the link (and keep the screenshots).

We should also avoid using links to our user directories as we keep changing them. Some of the links are throwing terminal errors which I'm assuming it's either because of an outdated config or code.

**Comment by jrchudy** [comment]
The readme has been updated to show working links and to remove links that were pointing to user directories when no example was in production. 

We should consider copying data from facebase and atlas-d2k to dev.derivacloud.org. Once we've done this, we can define a `plot-config.js` using that data for our examples.
