### ISSUE TITLE
React grid layout configuration validation

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/deriva-webapps#201]
We want to validate the new properties that are being added to the plot configuration. `grid_layout_config` and each control in `user_controls` should be checked for:
 - if those properties are required
   - if a property has defaults we can fall back to, then it isn't required and we should use the default when not defined
 - the property's expected type whether it's a string, array, object etc
   - if not defined properly, maybe we want to show a warning alert
   - fall back to default value
   - if property is required, alert should maybe be an error instead of a warning

The following is from a https://github.com/informatics-isi-edu/deriva-webapps/issues/161#issuecomment-1791397832

We want to list the properties in the `grid_layout_config`, each control in `user_controls`, and each layout in `layout` that are required to be defined as well as checking the type of the set value. We should be validating this list in the code and throwing proper errors when those properties are not defined. 

List of properties to validate:
 - `grid_layout_config`:
   - `cols` - might not need to be validated since we might have a default to use? 12 cols as default maybe?
     - fails validation for this control if not defined
       - **what does a failed validation mean?**
   - _please fill in more..._
 - `user_control`:
   - `uid` - required or can't map control to `$control_values` used for templating or map to an object in `layout`
     - fails validation for this control if not defined
   - `type` - required unless we want to assume a default is dropdown
     - we should probably enforce this as a requirement since other properties being defined depend on this being set
     - fails validation for this control if not defined
       - **what does a failed validation mean?**
         - don't add to set of user controls and don't load the control in the UI
         - put a warning in browser as alert OR warning in browser console
           - warning icon doesn't make sense since this control won't be displayed
           - error popup doesn't make sense since this shouldn't break the app
   - _please fill in more..._
 - `layout`:
   - `source_uid` - required or we don't know what control/plot to show
     - fails validation if not defined
       - **what does a failed validation mean?**
         - ignore this layout entry
         - put a warning in browser as alert OR warning in browser console
   - _please fill in more..._

Types of errors might include:
 - error modal popup
 - alert warning
 - browser console output
 - warning icon in the component that can't be loaded or have data fetched for
   - how we do this for facet panel:
      <img width="351" alt="image" src="https://github.com/informatics-isi-edu/deriva-webapps/assets/2932600/382f8f6f-ba32-46c6-9748-4f0fef51b9b6">
   - how chrome does it for developer tools:
      <img width="298" alt="image" src="https://github.com/informatics-isi-edu/deriva-webapps/assets/2932600/55fee43d-efd7-4f40-be96-7b4366ae7380">

We have 3 things to validate in the configuration language, how should failed validations be handled for these 3 cases? Should each case always be handled the same or would some controls erroring be handled differently?
 - `grid_layout_config`:
   - **what does a failed validation mean?**
 - `user_control`:
   - **what does a failed validation mean?**
 - `layout`:
   - **what does a failed validation mean?**

**Comment by KenyShah24** [comment]
We want to validate the new properties that are being added to the plot configuration. Following properties will be validated for appropriate parameters: `grid_layout_config`, `user_controls`, `grid_layout_config.layouts`, `plots`

We are validating this list in the code and throwing proper errors when those properties are not defined. 
List of properties which will be validated and errors that will be shown:
 - **`grid_layout_config`**
   - **_`cols`_** : It will be validated but no error will be thrown and default 'cols' = 12 will be used
   
 - **`user_controls`**:
   - **_`uid`_** (Required) : It will show a blocking error for local and global controls
<img width="956" alt="no_uid_error" src="https://github.com/informatics-isi-edu/deriva-webapps/assets/122313521/13c944b4-54a2-4cbc-8aa8-dede43580d0f">

  - **_`label`_** : Control will be displayed without any label and no error/warning will be shown
  
  - **_`request_info.url_pattern or request_info.data`_** (Required) : If neither of the 2 parameters are provided the control will not be shown and an alert with type 'warning' will be displayed.
<img width="958" alt="no_data_error" src="https://github.com/informatics-isi-edu/deriva-webapps/assets/122313521/62227989-6688-4e83-99be-1c0219562537">

   - **_`type`_** (Required) : The control won't be displayed if 'type' is missing and it will show an alert with type 'error' 
<img width="959" alt="image" src="https://github.com/informatics-isi-edu/deriva-webapps/assets/122313521/6f250b92-6d8c-45c1-b37b-9973cc0b495d">

 - **`layouts`**:
   - _**`source_uid`**_ (Required) : It will show the control/plot but without any layout applied to it and an alert with type 'warning' will be shown.
<img width="955" alt="image" src="https://github.com/informatics-isi-edu/deriva-webapps/assets/122313521/4095cd93-e34e-4180-ab70-6157340a45b1">

 - _**`[h, w, x, y] `**_ (Required) : The control won't be displayed and an alert with type 'warning' will be shown if any of these parameters are missing from the layout property
<img width="949" alt="invalid_layout_error" src="https://github.com/informatics-isi-edu/deriva-webapps/assets/122313521/1984bfd1-7474-4557-ba18-da7f697bc073">

 - **`plots`**:
   - _**`uid`**_ : Plot will be shown by generating a default uid and an alert with type 'warning' will be displayed on top.
<img width="950" alt="no_uid_plot_error" src="https://github.com/informatics-isi-edu/deriva-webapps/assets/122313521/a9ea1cc3-6bbd-4ed2-8d47-917cb084f512">

- Additionally, if multiple plots or controls, or a combination thereof, share the same uid, only the last defined instance will be considered, with a corresponding warning alert displayed.
<img width="950" alt="same_uid_error" src="https://github.com/informatics-isi-edu/deriva-webapps/assets/122313521/31dffbba-811f-447b-a2fb-6a8704600df5">
