### ISSUE TITLE
Unified Error Handling

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/deriva-webapps#30]
We want the deriva webapps to use all the existing error handlings that we have in ermrestjs and chaise. This includes the retry logic and also the error modals that are displayed in chaise. To achieve these we need to do the following:

1. ermrestjs must be included in the list of dependencies.

2. ERMrest module must be available and configured.

  - If it's an AngularJS app, you just need to inject the `ERMrest` module in the list of dependencies. ermrestjs will configure the http and promise modules of ermrestjs to be the $http and $q modules of AngularJS.

  - If it's not an AngularJS app, you need to configure ERMrest module by passing `http` and `q` modules to `ERMrest.configure` function. They should look the same as AngularJS [`$http`](https://docs.angularjs.org/api/ng/service/$http) and [`$q`](https://docs.angularjs.org/api/ng/service/$q) modules.
      - The current version of `q` bundled with `ermrestJS` is sufficient, but `request-q` is not. See the treeview app for more details on configuring `ermrestJS`. `Request-q` is a module maintained by us. It currently is set up to require `requireJS` which is causing some issues. We need to make changes to that library.

4. Use the following format for getting the http module and sending the request.  To be able to log the request you should also provide a specific header in your request. The following is how a http request would look like with logging. I have listed all the values that we are currently logging in ermrestjs. Most of them are not applicable in any of the deriva web-apps.

  ```javascript
    // getting the service object and http module:

    var ermrsetServiceUrl = "example.com/ermrest";

    // the contextHeaderParams will be logged with every request that you will send
   var contextHeaderParams = {"cid": "deriva-app-name"};
    
   // with this API you can access http module and also get Catalog and all it's table, etc.
   // service.catalogs.get("catalog-id") will return a promise that will be resolved with the catalog
   // service.http will return the http module that you can use for sending requests
    var server = ERMrest.ermrestFactory.getServer(ermrestServiceUrl, contextHeaderParams);

    // log stuff
    var headers = {};
    headers[ERMrest.contextHeaderName] = {
      schema_table: "schema:table", // the name of schema and table in `<schema>:<table>` format 
      action: "", // a string representing the type of request. Something unique throughout the whole ermrestjs and chaise.
      pid: "", // not sure if we need this
      wid: "", // not sure if we need this
      page_size: 2, // (not required) the number of requested rows
      facet: , //  (not required) the facet in the url 
      filter: , // (not required) the filter in the url
    };

    // sending the request
    var uri = "the ermest uri";
    server.http.get(uri, {headers: headers}).then(function success (res) {
      ...
    }).catch(function (err) {
       throw ERMrest.responseToError(err);
    });
  ```

6. If we want the error handling that we have for chaise in these apps, they must be rewritten as AngularJS apps. Then we must make sure chaise errors.js and its dependencies are all included.

7. (chaise) For now we want a simple `CustomError` class in the chaise that deriva webapps can use. This way each app can throw that error with their own specific attributes (error title, message, etc.) and chaise should just show the same modal with the given attributes.

**Comment by hongsudt** [comment]
@vipul-21 verify that this has been done in the boolean search and is part of the documentation in this repo. If so, close the issue.

**Comment by vipul-21** [comment]
@hongsudt This has been done in boolean search and it's in the documentation as well. Closing the issue.
