### ISSUE TITLE
allow use of chaise navbar app

### ISSUE THREAD

**Issue by crisaless** [informatics-isi-edu/deriva-webapps#48]
Once the navbar app for GUDMAP/RBK is ready (there are some integration bugs with the jekyll site I'm working out) it would be great to be able to add the navbar to the webapps (ie, boolean search).

**Comment by hongsudt** [comment]
@crisaless this is done.. Can you please review and report any problem to @Divyata-Singh .

**Comment by hongsudt** [comment]
@vipul-21 please verify this by browsing through the navbar while in boolean search. Try selecting menu at multiple dept.

**Comment by vipul-21** [comment]
@hongsudt The navbar is working fine in boolean search. Closing the issue.
