### ISSUE TITLE
Check Boolean Search URL Length Dynamically 

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/deriva-webapps#49]
Currently boolean search is setting a fix limit on the number of queries that users can add. This has been done to make sure we're not going over the path length limitation in ermrestjs/chaise. We can improve this and do the length checking in boolean search. We might be able to allow more queries based on different sets of input. The following are the possible solutions that I could think of:

1. Since we're already including ermrestjs we could technically resolve a `Reference` object and then get the actual url that will be used in chaise. This is possible but not feasible. It's overkill since resolving a reference means doing the whole introspection in boolean search, which can be very expensive. 

2. With the same inputs that you're using to create a path, you can create a location object. The location object can give you the ermrest url. Although this url is not the exact url that we're sending to ermrest. The actual url will have additional projections to include the foriegn key data. Since these additional projections are constant, you can add an offset for the length check.

```javascript


// service: http://dev.rebuildingakidney.org/ermrest
var location = ERMrest.createLocation(service, catalogId, schemaName, tableName, null, cfacets);

// needs to be adjusted
var offset = 1200;

If (location.ermrestCompactPath + offset > ERMrest.URL_PATH_LENGTH_LIMIT) {
  // over the limit
}
```

The offset will be different based on the deployment (schema, table, column, and foreign keys might be different). To find the offset,

1. Go to recordset page of the table that boolean search is based on (in this case `Gene_Expression:Specimen`).

2. Open the network tab, clear all facets, and reload the page.

3. Find the main entity request. It should look like the following

  ```
 
 https://dev.rebuildingakidney.org/ermrest/catalog/2/attributegroup/M:=Gene_Expression:Specimen/
  F15:=left(Fixation)=(Vocabulary:Fixation:Name)/$M/
  F14:=left(Provenance)=(Common:Provenance:Name)/$M/
  ...
 Stage_Ordinal,RID;M:=array_d(M:*),
 F15:=array_d(F15:*),
 F14:=array_d(F14:*),
 ...
  @sort(Stage_Ordinal,RID)?limit=26
  ```
   [example](https://dev.rebuildingakidney.org/ermrest/catalog/2/attributegroup/M:=Gene_Expression:Specimen/F15:=left(Fixation)=(Vocabulary:Fixation:Name)/$M/F14:=left(Provenance)=(Common:Provenance:Name)/$M/F13:=left(Consortium)=(Common:Consortium:Name)/$M/F12:=left(Sex)=(Vocabulary:Sex:Name)/$M/F11:=left(Assay_Type)=(Vocabulary:Assay_Type:Name)/$M/F10:=left(Cell_Line)=(Cell_Line:Cell_Line:Name)/$M/F9:=left(Parent_Specimen)=(Gene_Expression:Specimen:RID)/$M/F8:=left(Representative_Image)=(Gene_Expression:Image:RID)/$M/F7:=left(Principal_Investigator)=(Common:Principal_Investigator:Person)/$M/F6:=left(Species)=(Vocabulary:Species:Name)/$M/F5:=left(Wild_Type)=(Gene_Expression:Wild_Type:Name)/$M/F4:=left(Phenotype)=(Vocab:Kidney_Phenotype:Name)/$M/F3:=left(Preparation)=(Vocab:Preparation:Name)/$M/F2:=left(Stage_ID)=(Vocabulary:Developmental_Stage:ID)/$M/F1:=left(Embedding)=(Vocabulary:Embedding:Name)/$M/Stage_Ordinal,RID;M:=array_d(M:*),F15:=array_d(F15:*),F14:=array_d(F14:*),F13:=array_d(F13:*),F12:=array_d(F12:*),F11:=array_d(F11:*),F10:=array_d(F10:*),F9:=array_d(F9:*),F8:=array_d(F8:*),F7:=array_d(F7:*),F6:=array_d(F6:*),F5:=array_d(F5:*),F4:=array_d(F4:*),F3:=array_d(F3:*),F2:=array_d(F2:*),F1:=array_d(F1:*)@sort(Stage_Ordinal,RID)?limit=26)

4. The offset is whatever comes after the `M:=Gene_Expression:Specimen`. In this example the length is 1155 characters. Round up that number just to be safe.

**Comment by hongsudt** [comment]
@vipul-21 check whether the dynamic url checking has been done. Please test manually. If this is done, then comment and close the issue.

**Comment by vipul-21** [comment]
@hongsudt The dynamic url checking is not done. The url limit is being checked only when the search query is submitted.

**Comment by jrchudy** [comment]
Added comment in code for where to add this check and a `Note` that we won't change it in the current implementation.
