### ISSUE TITLE
boolean search navbar is buggy

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/deriva-webapps#53]
There is a buggy logic within the interaction of treeview with the main page.. Once I use the search to search for terms that require auto-scroll to the bottom, navbar disappears from the page. Once that happens, refresh wouldn't bring back navbar..

**Comment by hongsudt** [comment]
@Divyata-Singh If this issue has been fixed, can you please close the issue?

**Comment by hongsudt** [comment]
Better yet, @vipul-21 can you verify whether this issue has been fixed?

**Comment by vipul-21** [comment]
@hongsudt The issue has been fixed. Closing the issue.
