### ISSUE TITLE
heatmap: better handle the 404 error

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/deriva-webapps#74]
https://dev.gudmap.org/deriva-webapps/heatmap/#2/Gene_Expression:Array_Data_view/NCBI_GeneID=1
Throws a very weird error:
```
Configuration Errors
Change the following in the heatmap-config.js file:    
Error while reading data from Ermrestjs
```
In this case, it seems like NCBI_GeneID=1 doesn’t exist in the table.. 

We should handle this error better.. 

Note: 
- GeneID=17740 will work fine. 
- Use record app to check whether the data exist: https://www.gudmap.org/chaise/record/#2/Gene_Expression:Array_Data_view/NCBI_GeneID=1

**Comment by vipul-21** [comment]
On clicking the above mentioned link. I am getting the following error:
1. When not logged in.
<img width="1440" alt="Screen Shot 2019-08-21 at 11 06 39 AM" src="https://user-images.githubusercontent.com/8600441/63456602-24556400-c404-11e9-979e-810ca9202ba2.png">

2. When logged in.
<img width="1440" alt="Screen Shot 2019-08-21 at 11 07 40 AM" src="https://user-images.githubusercontent.com/8600441/63456633-3b945180-c404-11e9-8755-3d20835fb91f.png">

There was no `Configuration Error`. @hongsudt Can you please let me know how to replicate the issue if it still exists.

**Comment by jrchudy** [comment]
The issue is with the deriva-webapps link above not the chaise link.

https://dev.gudmap.org/deriva-webapps/heatmap/#2/Gene_Expression:Array_Data_view/NCBI_GeneID=1

When navigating to this link, make sure your ad blocker is turned off for that domain so that you don't get an angular error and can instead see the DB error.

**Comment by vipul-21** [comment]
There are 2 cases to handle for 404 Not Found:
1. There is no heatmap data available for the given “id” (but the record with that id exists)
2. There is no record with the given “id” (and therefore there is no heatmap data that exists)

- [ ] Need to find out(in the code base)  if we actually check for the record existence in heatmap, if that's the case then the error for both the cases can be different.
For 1. the error will be "There is no heatmap data for the given 'id'"
For 2. the error will be "No record for the given 'id'"

If the above is not true, then we need to display the same error for both the cases "There is no heatmap data for the given 'id'"
