### ISSUE TITLE
plot app: js error on safari

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/deriva-webapps#77]
@vipul-21 There is a problem with the app on safari.. It throws the following error:
[$rootScope:inprog] http://errors.angularjs.org/1.6.9/$rootScope/inprog?p0=%24digest

Here is the link that fails:
https://dev.rebuildingakidney.org/~vipul/deriva-webapps/plot/

**Comment by vipul-21** [comment]
This issue was resolved with the PR #78.
