### ISSUE TITLE
Plot: More adjustments for plot app

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/deriva-webapps#79]
Based on the conversation I had with @hongsudt yesterday, there are a few more things to address for the plot app. These are taken from some of the PR comments I previously left and others from discussion about error handling strategies.

- [x] add a margin at the top of each graph
- [x] defining chaise-config as `<script src='/chaise/chaise-config.js'></script>`
   - This will always use the chaise-config that's at the server root (the one used by master). This is fine for deployments using master (dev, staging, production) but makes it harder for us to test chaise config features and changes because our config will be ignored.
   - In the below issue, I use the above syntax for `sample-navbar.html`, but that's for an example. In that case, the html file can be root or 4 levels deep, so the developer would have to hardcode chaise config based on location to the `sample.html` .
   - I think in this case, we want the webapps to use a relative path that assumes the apps will be in a folder structure like:
      - `/html/chaise/chaise-config.js`
      - `/html/deriva-webapps/<webapp>`
   - this comment goes with issue #67 
 - [x] regarding the session check, we need to rethink the error handling strategy in this case. 
   - We can't simply assume the user needs to be logged in to view the data, some of the presented data could be accessible anonymously
   - if we were to use the `Reference` API in `ermrestJS`, this more robust error handling that chaise has would be used. We have checks in `ermrest.resolve` to handle some of these cases to better provide errors for the users.
 - [ ] consider the case that Mike raised about formatting values
   - we had a function to strip values from a string and parse them into an integer, this might have worked for a very specific case, but in general this will most likely not be the case
   - either this "function" to modify the input is a configuration
   - OR, we define a strategy that plot app will always use that's more globally safe and data modelers will have to align their data to that strategy

**Comment by vipul-21** [comment]
The PR #80 contains the above adjustments.
