### ISSUE TITLE
Fix boolean search scroll issue

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/deriva-webapps#82]
It seems like boolean search was relying on chaise `app.css`. With the recent changes to the chaise `app.css`, the scrollbar of boolean search app is broken and we should fix it.

**Comment by hongsudt** [comment]
@jrchudy @RFSH can one of you fix this bug? I don't have anyone else to work on this.

**Comment by hongsudt** [comment]
I just realized that this is in-review.. @RFSH if this problem no longer exists on production, please close the issue.
