### ISSUE TITLE
Update chaise dependencies and build process

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/deriva-webapps#90]
We recently updated the Chaise and ERMrestJS build process. With the new change, we're minifying all the assets. We also updated the Makefile parameters.

We should apply the same changes to deriva-webapps. This will increase their performance and also ensures a more robust way of including chaise. We should not blindly assume Chaise's relative path in deriva-webapps and instead, we should do the same thing that we did for the navbar app (using `chaise-dependencies.html` file that is generated by Chaise).

**Comment by jrchudy** [comment]
No longer relevant for reactJS
