### ISSUE TITLE
Support for Violin Plots

### ISSUE THREAD

**Issue by DamCousik** [informatics-isi-edu/deriva-webapps#93]
The aim is to create a new plot type (Violin Plots) that will provide a more detailed description and visual representation of the data. The following link contains violin plots similar to what we would like to support. The below page uses D3.js which we would modify to ensure the Plotly config.js file supports.

https://gtexportal.org/home/gene/TBP#geneExpression

![image](https://user-images.githubusercontent.com/65321179/90289736-5b9cfc00-de31-11ea-97fe-41d501edd869.png)

Currently, data in RBK is represented as bars/histograms/pie chart as follows:
Link to a bar chart:
https://dev.rebuildingakidney.org/deriva-webapps/plot/
Link to a pie chart (plot app in deriva-webapps):
https://dev.rebuildingakidney.org/deriva-webapps/plot/?config=rbk-config
Link to a histogram plot in faceting:
https://dev.rebuildingakidney.org/chaise/recordset/#2/Gene_Expression:Specimen/*::facets::N4IghgdgJiBcDaoDOB7ArgJwMYFM4gCUBZAFRABoQNIBzHJOREAWzAA98AmABh4FpuAdgEAOEgEYALLEkBmWLO4A6bqoGDYqiiwCWELt3Ei+4zgNkSRC6ZwCcKtdytaAvgF13LoA@sort(RCT::desc::,Stage_Ordinal,RID)

Plotly.js can be used to represent data as violin plots with sample data as per the below page as we currently do not have data that could be used for this plot.
https://plotly.com/javascript/violin/

**Comment by jrchudy** [comment]
Violin plot support has been implemented and merged into master.
https://dev.rebuildingakidney.org/deriva-webapps/plot/?config=violin-plot
