### ISSUE TITLE
TPM Expression Plot: Scale-log incorrect

### ISSUE THREAD

**Issue by GHAStVHenry** [informatics-isi-edu/deriva-webapps#97]
Standard in the field when log TPM (for the the y-axis) to do log(TPM+1)

This is because log of zero TPM values causes and error (doesn't display correctly).

Here is an example of this elsewhere:
https://gtexportal.org/home/gene/KLK3
(change the scale to log and look at the y-axis)
![image](https://user-images.githubusercontent.com/38675268/93814484-35316400-fc1a-11ea-891e-897a18c3022a.png)

Also...
* TPM can only have positive values, so GTEx, limits y-axis to zero... I don't have a strong feeling about this, but something to consider also
* Currently the plot is box blot + violin plot... both are different representation of the same data... both are not necessary, one or the other (personally, I like having both when displaying a lot of data such as single cell... but here with only the few replicates per group per study, I'm not sure displaying both is that useful)
* Similarly: I'm not sure having the scatter plot (jitter) next to the violin/box is that useful... if you keep the scatter, I argue adding on top of the violin/box plot... or removing scatter completely

background:
This is a standard practice called adding a "pseudocount". Reasonable values of TPM can be in the thousands... adding 1 to every value won't significantly change the data, and it also changes ALL the data in the same way, and prevents a problem in trying to log(0)

**Comment by jrchudy** [comment]
We have added a selector to change from linear to log, all TPM values are increased by 1 now, and the scatter points are inside the violin/box instead of beside it.

We are going to continue showing both violin and box by default since this can be changed in the configuration. Same can be said about limiting the yaxis so it doesn't go below 0.
